version: 0.2

phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u silvesterp -p Zaq123zaq
      - export KUBECONFIG=$HOME/.kube/config
  build:      
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker image build -t flaskapp:latest .
      - docker tag flaskapp:latest silvesterp/flaskapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push silvesterp/flaskapp:latest
      - export AWS_ACCESS_KEY_ID=AKIA2FQMU6QBQ2UELAVP
      - export AWS_SECRET_ACCESS_KEY=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
      - export AWS_EXPIRATION=900
      - aws eks update-kubeconfig --name newcluster
      - kubectl apply -f deploy.yaml --force
      - kubectl rollout restart deploy  flask-deploy
      - kubectl apply -f service.yaml
      - kubectl get svc