apiVersion: v1
kind: Service
metadata:
  name: flaskapp-serveic
spec:
  selector:
   name: flaskapp
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer